---
# Generell:
#  use true / false to activate / deactivate functions
# Do you want to use custom join / Leave messages?
# If true you can change it in messages.yml
custom-joinmessage: true
custom-quitmessage: true

# Do you want to allow dropping on your server?
allow-dropping: false

# Can anyone consume (eat / drink) items in your lobby
allow-consume: false

# Do you allow crafting in Lobby?
allow-crafting: true

# Can player interact with other blocks? (Touch it)
# Lobbyitem interact will work without `true` too
allow-interact: true

# Do you allow death in lobby?
# Notice: Player will lose their inventory
allow-death: false

# Do you allow Damage (PvP Damage, Falling-damage, ...)
allow-damage: true

# Can player get hunger in Lobby?
allow-hunger: false

# Last step: Do you want player to chat in the Lobby without permission `lobby.chat` ?
allow-chat: true

# Lobby level (for /hub)
lobby-level: "world"

# Item names
players_visible: "§r§fPlayers visible"
players_invisible: "§r§fPlayers invisible"
custom: "§r§fCustom"
teleporter: "§r§fTeleporter"
perks: "§r§fPerks"
info: "§r§fInfo"

# Command for the "Custom" item
# {asplayer} to execute as the user
custom_command: "/help{asplayer}"

# All servers for the navigator
# -- Example - Fomat -- 
# servers: 
#  - ["Server1", 123.456.789.123, 19132]
#  - ["Server2", "google.de, 34762"]

servers:
 - ["WertzuiGames", "wertzuigames.de", 19132]
 - ["WertzuiGames", "wertzuigames.de", 19132]
...
